#!/usr/bin/env python3

from wolwolf import *

if __name__ == "__main__":
    config = Config()
    logger = Logger(config)
    logger.info("Starting server..")
    ws = WolwolfServer(config, logger)
    ws.run()
